//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod collections;
pub mod entries;
pub mod entry_boolean_values;
pub mod entry_date_time_values;
pub mod entry_number_list_values;
pub mod entry_number_values;
pub mod entry_object_values;
pub mod entry_relation_values;
pub mod entry_text_list_values;
pub mod entry_text_values;
pub mod entry_typst_text_values;
pub mod fields;
pub mod sea_orm_active_enums;
pub mod users;
