//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    juniper :: GraphQLEnum,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "data_types")]
pub enum DataTypes {
    #[sea_orm(string_value = "text")]
    Text,
    #[sea_orm(string_value = "typst_text")]
    TypstText,
    #[sea_orm(string_value = "boolean")]
    Boolean,
    #[sea_orm(string_value = "number")]
    Number,
    #[sea_orm(string_value = "relation")]
    Relation,
    #[sea_orm(string_value = "date_time")]
    DateTime,
    #[sea_orm(string_value = "text_list")]
    TextList,
    #[sea_orm(string_value = "number_list")]
    NumberList,
    #[sea_orm(string_value = "object")]
    Object,
}
